### ISSUE TITLE
Do fizzbuzz with if, for

### ISSUE THREAD

**Issue by ulgoon** [ulgoon/probable-journey#1]
I want to make python file to print fizz, buzz or fizzbuzz with conditions

While I goes up 1 to 17,
- print 'fizz' if I is times of 3
- print 'buzz' if I is times of 5
- print 'fizzbuzz' if i is times of 15
- else, print I

## Tasks

- [x] Create fizzbuzz.py
- [x] print 'fizz' if I is times of 3
- [x] print 'buzz' if I is times of 5
- [x] print 'fizzbuzz' if I is times of 15
